export const SET_USER_ID: "SET_USER_ID" = "SET_USER_ID";
export const SET_NEW_SPEED: "SET_NEW_SPEED" = "SET_NEW_SPEED";
export const SET_DIMENSION: "SET_DIMENSION" = "SET_DIMENSION";
export const SAVE_ROUND: "SAVE_ROUND" = "SAVE_ROUND";
export const GO_TO_RESULTS: "GO_TO_RESULTS" = "GO_TO_RESULTS";
export const STORE_IN_DB: "STORE_IN_DB" = "STORE_IN_DB";
export const STORE_IN_DB_SUCCESS: "STORE_IN_DB_SUCCESS" =
  " STORE_IN_DB_SUCCESS";
export const STORE_IN_DB_ERROR: "STORE_IN_DB_ERROR" = "STORE_IN_DB_ERROR";
export const GO_TO_USER_ID_INPUT: "GO_TO_USER_ID_INPUT" = "GO_TO_USER_ID_INPUT";
export const SAVE_CLICK: "SAVE_CLICK" = "SAVE_CLICK";
export const RESET_CLICKS: "RESET_CLICKS" = "RESET_CLICKS";
