export const SET_USER_ID: "SET_USER_ID" = "SET_USER_ID";
export const PRE_TRAINING: "PRE_TRAINING" = "PRE_TRAINING";
export const START_TRAINING: "START_TRAINING" = "START_TRAINING";
export const WRITE_ELEMENTS_TO_STATE: "WRITE_ELEMENTS_TO_STATE" =
  "WRITE_ELEMENTS_TO_STATE";
export const WRITE_PATTERN_TO_STATE: "WRITE_PATTERN_TO_STATE" =
  "WRITE_PATTERN_TO_STATE";
export const SELECT_ELEMENT: "SELECT_ELEMENT" = "SELECT_ELEMENT";
export const START_USER_INPUT: "START_USER_INPUT" = "START_USER_INPUT";
export const SHOW_RESULTS: "SHOW_RESULTS" = "SHOW_RESULTS";
export const START_COUNTDOWN: "START_COUNTDOWN" = "START_COUNTDOWN";
export const START_TIME: "START_TIME" = "START_TIME";
export const STOP_TIME: "STOP_TIME" = "STOP_TIME";
export const SAVE_INPUT: "SAVE_INPUT" = "SAVE_INPUT";
export const NEXT_ROUND: "NEXT_ROUND" = "NEXT_ROUND";
export const WRITE_TO_RESULTS: "WRITE_TO_RESULTS" = "WRITE_TO_RESULTS";
export const SET_NEW_SPEED: "SET_NEW_SPEED" = "SET_NEW_SPEED";
export const SET_NEW_OPACITY: "SET_NEW_OPACITY" = "SET_NEW_OPACITY";
export const SET_ROLLBACK: "SET_ROLLBACK" = "SET_ROLLBACK";
export const STORE_IN_DB: "STORE_IN_DB" = "STORE_IN_DB";
export const STORE_IN_DB_SUCCESS: "STORE_IN_DB_SUCCESS" = "STORE_IN_DB_SUCCESS";
export const STORE_IN_DB_ERROR: "STORE_IN_DB_ERROR" = "STORE_IN_DB_ERROR";
export const GO_TO_USER_ID_INPUT: "GO_TO_USER_ID_INPUT" = "GO_TO_USER_ID_INPUT";
export const SET_DIMENSION: "SET_DIMENSION" = "SET_DIMENSION";
export const ADD_POINTS: "ADD_POINTS" = "ADD_POINTS";
export const SET_NEW_POINTS: "SET_NEW_POINTS" = "SET_NEW_POINTS";
export const SET_NEW_PATTERNLENGTH: "SET_NEW_PATTERNLENGTH" =
  "SET_NEW_PATTERNLENGTH";
export const SAVE_CLICK: "SAVE_CLICK" = "SAVE_CLICK";
