export const SET_USER_ID: "SET_USER_ID" = "SET_USER_ID";
export const SET_DIMENSION: "SET_DIMENSION" = "SET_DIMENSION";
export const SAVE_ROUND: "SAVE_ROUND" = "SAVE_ROUND";
export const GO_TO_RESULTS: "GO_TO_RESULTS" = "GO_TO_RESULTS";
export const STORE_IN_DB: "STORE_IN_DB" = "STORE_IN_DB";
export const STORE_IN_DB_SUCCESS: "STORE_IN_DB_SUCCESS" =
  " STORE_IN_DB_SUCCESS";
export const STORE_IN_DB_ERROR: "STORE_IN_DB_ERROR" = "STORE_IN_DB_ERROR";
export const GO_TO_USER_ID_INPUT: "GO_TO_USER_ID_INPUT" = "GO_TO_USER_ID_INPUT";
export const NEXT_ROUND: "NEXT_ROUND" = "NEXT_ROUND";
export const SET_ROLLBACK: "SET_ROLLBACK" = "SET_ROLLBACK";
export const CHANGE_ACTIVE_ROWS: "CHANGE_ACTIVE_ROWS" = "CHANGE_ACTIVE_ROWS";
export const CHANGE_NUMBER_OF_ACTIVE_ROWS: "CHANGE_NUMBER_OF_ACTIVE_ROWS" =
  "CHANGE_NUMBER_OF_ACTIVE_ROWS";
export const START_GAME: "START_GAME" = "START_GAME";
export const SAVE_CLICK: "SAVE_CLICK" = "SAVE_CLICK";
export const CHANGE_INCENTIVES: "CHANGE_INCENTIVES" = "CHANGE_INCENTIVES";
export const RESET_CLICKS: "RESET_CLICKS" = "RESET_CLICKS";
export const RESET_HITS_AND_MISSES: "RESET_HITS_AND_MISSES" =
  "RESET_HITS_AND_MISSES";
export const HIT_ELEMENT: "HIT_ELEMENT" = "HIT_ELEMENT";
export const MISS_ELEMENT: "MISS_ELEMENT" = "MISS_ELEMENT";
export const TOGGLE_INCENTIVES: "TOGGLE_INCENTIVES" = "TOGGLE_INCENTIVES";
export const CREATE_ELEMENT: "CREATE_ELEMENT" = "CREATE_ELEMENT";
export const CHANGE_NUMBER_OF_ELEMENTS_TO_CREATE: "CHANGE_NUMBER_OF_ELEMENTS_TO_CREATE" =
  "CHANGE_NUMBER_OF_ELEMENTS_TO_CREATE";
